### PR TITLE
Sdk/3590

### PR DESCRIPTION
**Pull request by mattdangerw**
[endlessm/eos-sdk#3590]

### CODE REVIEW

**Comment by cosimoc** [comment]
There's probably a few more commits that should be picked here:
https://git.gnome.org/browse/gtk+/commit/gtk/gtkwindow.c?id=f7cc4abbad76f354cdc740e7fb9192719f72a89a
https://git.gnome.org/browse/gtk+/commit/gtk/gtkwindow.c?id=6d77b9f3162d9f3d9ea214b765b6f937e4439237
https://git.gnome.org/browse/gtk+/commit/gtk/gtkwindow.c?id=ef8a5fc5425445b173ec33035f58ed68d790f137
https://git.gnome.org/browse/gtk+/commit/gtk/gtkwindow.c?id=c360b5fb498985ca8d351e9c9d518b0d78b834ba

**Comment by cosimoc** [comment]
Some more:
https://git.gnome.org/browse/gtk+/commit/gtk/gtkwidget.c?id=d46b67dc79485accfc1e06403ec38458a7d2836d
https://git.gnome.org/browse/gtk+/commit/gtk/gtkwidget.c?id=580ea227a6bb19ad6c6d4766b3a36dbad24583f3, https://git.gnome.org/browse/gtk+/commit/gtk/gtkwidget.c?id=ab5dbfd1f1fec1c8e62460236769ffd80cad4a54, https://git.gnome.org/browse/gtk+/commit/gtk/gtkwidget.c?id=a50baba16058ea86c95269c2eff24a1c97ec34d2 and https://git.gnome.org/browse/gtk+/commit/gtk/gtkwidget.c?id=efc899bd2b2a351221cd2c455773f62defc06b9c (fairly big changes, but also a nice speed up probably)

**Comment by mattdangerw** [comment]
Also https://git.gnome.org/browse/gtk+/commit/?id=c360b5fb498985ca8d351e9c9d518b0d78b834ba

**Comment by mattdangerw** [comment]
Oh wait that was on you list already.

**Comment by mattdangerw** [comment]
@cosimoc so the latter bunch of commit you picked out is a little harder to cherry-pick.

To avoid merge conflicts you need
https://git.gnome.org/browse/gtk+/commit/?id=ebdf5f581d4e93c577f4cdb2e47e30e393e61157
https://git.gnome.org/browse/gtk+/commit/?id=e8aa9b0440e03e7002323922f862342db51c5f32
https://git.gnome.org/browse/gtk+/commit/?id=7a05016d938ada16b25b6a7b8683e98f107a5a6f

We could also handle some merge conflicts, but I was trying to avoid homebrew versions of upstream commits on our branch. I'll plan on bringing those in for now.

It also causes a regression with drawing a button in an overlay over a webview, investigating why now.

**Comment by cosimoc** [comment]
@mattdangerw Don't spend too much time trying to pick those commits right now if they have complications or don't apply cleanly - we can always land this first and do more experiments once the dust settles.

**Comment by mattdangerw** [comment]
@cosimoc sounds good; I agree. I'll drop the second batch right now, the disappearing overlay arrow does not persist on `gnome/master`, so we may be missing another commit to bring in there. I'll leave that for a future investigation.

**Comment by mattdangerw** [comment]
So just added the first batch of commit above. Also did some semi automated `git log` + `sed` magic to make sure our commit history order matches `gnome/master`.

**Pull request merged**
