### PR TITLE
Revert "theme: add Endless-specific customizations"

### PR DESCRIPTION
**Pull request by andrunko**
This reverts commit 2a29bc3c28a57bd3ae41b9eb76b0af8753356970.

https://phabricator.endlessm.com/T29566

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
retest this please

**Comment by GeorgesStavracas** [comment]
Looks like this simple revert isn't that much simple... it's breaking the `flipping-icons.ui` test

**Comment by andrunko** [comment]
From local tests looks like this test is also failing on our current master, am checking if I can find a fix but it doesnt look like an issue with this PR.

**Comment by GeorgesStavracas** [comment]
I see. Let's not block on it then.

**Pull request merged**
