### PR TITLE
DO NOT MERGE: Upgrade to 3.22.4

### PR DESCRIPTION
**Pull request by ptomato**
https://phabricator.endlessm.com/T14197

### CODE REVIEW

**Comment by mattdangerw** [comment]
Might be good to try and get Sam's AM_DISTCHECK commit upstream. Gtk now requires a version of automake that works the patch, so we should be able to get that on master.

**Comment by mattdangerw** [comment]
Looks good to me! I wonder if it makes sense to squash down all of my "theme:" commits with Cosimo's "Add WM theme customizations for Endless" for easier rebasing in the future.

**Comment by mattdangerw** [comment]
There's a typo in https://github.com/endlessm/gtk/pull/54/commits/96a226ed633c153187f70dcf842600ae5646b2cd
"checking he current" -> "checking the current"

**Comment by ptomato** [comment]
I found that Sam's change is already upstream — the only thing left in that commit was the actual Automake version bump, which is probably not important enough to send a patch for.

I'll squash the theme commits and fix the typo.

**Pull request closed without merging**
